services:
    _default:
        autowire: true
        autoconfigure: true

    Zeggriim\YousignWebhookBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,Tests}'

    Zeggriim\YousignWebhookBundle\Webhook\YousignRequestParser:
        arguments:
            $secret: '%yousign.webhook.secret%'

    Zeggriim\YousignWebhookBundle\Controller\YousignWebhookController:
        tags: ['controller.service_arguments']