services:
    _defaults:
        autowire: true
        autoconfigure: true

    Zeggriim\YousignWebhookBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception,RemoteEvent,Resources,Tests}'

    Zeggriim\YousignWebhookBundle\Security\YousignSignatureVerifier:
        arguments:
            $secret: '%yousign.webhook.secret%'

    Zeggriim\YousignWebhookBundle\Security\YousignIpChecker:
        arguments:
            $allowedIps: '%yousign.webhook.allowed_ips%'

    Zeggriim\YousignWebhookBundle\Controller\YousignWebhookController:
        arguments:
            $logger: '@?logger'
            $type: '%yousign.webhook.type%'
        tags:
            - 'controller.service_arguments'
            - { name: monolog.logger, channel: yousign }
