services:
    _defaults:
        autowire: true
        autoconfigure: true

    Zeggriim\YousignWebhookBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,Tests}'

    Zeggriim\YousignWebhookBundle\Security\YousignSignatureVerifier:
        arguments:
            $secret: '%yousign.webhook.secret%'

    Zeggriim\YousignWebhookBundle\Controller\YousignWebhookController:
        tags: ['controller.service_arguments']