name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main] # cette syntaxe est correcte
        types: [opened, synchronize, reopened] # optionnel mais plus explicite

jobs:
    checks:
        name: PHPStan, PHP CS Fixer & PHPUnit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  coverage: none

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist

            - name: Run PHPStan
              run: ./vendor/bin/phpstan analyse --memory-limit=512M

            - name: Run PHP CS Fixer
              run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

            - name: Run PHPUnit
              run: ./vendor/bin/phpunit --no-coverage
